version: "3.9"

services:
  app:
    image: fitrakz/yomutext:latest
    ports:
      - "8005:8000"
    deploy:
      replicas: 1
    networks:
      - app-net

networks:
  app-net:
    driver: overlay
