name: Devscale Assignment

on:
  push:
    branches:
      - devscale/assignment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}

    - name: Deploy to Swarm
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SWARM_HOST }}
        username: ${{ secrets.SWARM_USERNAME }}
        key: ${{ secrets.SWARM_SSH_PRIVATE_KEY }}
        script: |
          docker service update --image ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }} assignment-devscale_app
